// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCS4vVWV-pLDmz5Q6iNeTGHwgvSfzYiCBQ',
    appId: '1:302226122621:web:2ce211c70f8d7b3cff8e14',
    messagingSenderId: '302226122621',
    projectId: 'learner-d733d',
    authDomain: 'learner-d733d.firebaseapp.com',
    storageBucket: 'learner-d733d.appspot.com',
    measurementId: 'G-JKQ0P7RJY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8nJwJjXh21V7PzUgZRxiKNCZFim1y4MU',
    appId: '1:302226122621:android:a7a7834e6ff650cbff8e14',
    messagingSenderId: '302226122621',
    projectId: 'learner-d733d',
    storageBucket: 'learner-d733d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFbGDGFkf3dK7N4CUoPfy7gEBuCsmhL2E',
    appId: '1:302226122621:ios:a762ec7f1b4c63d4ff8e14',
    messagingSenderId: '302226122621',
    projectId: 'learner-d733d',
    storageBucket: 'learner-d733d.appspot.com',
    iosBundleId: 'com.example.learner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFbGDGFkf3dK7N4CUoPfy7gEBuCsmhL2E',
    appId: '1:302226122621:ios:a762ec7f1b4c63d4ff8e14',
    messagingSenderId: '302226122621',
    projectId: 'learner-d733d',
    storageBucket: 'learner-d733d.appspot.com',
    iosBundleId: 'com.example.learner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCS4vVWV-pLDmz5Q6iNeTGHwgvSfzYiCBQ',
    appId: '1:302226122621:web:814ffb97d3f9065eff8e14',
    messagingSenderId: '302226122621',
    projectId: 'learner-d733d',
    authDomain: 'learner-d733d.firebaseapp.com',
    storageBucket: 'learner-d733d.appspot.com',
    measurementId: 'G-VRVXLDCN5J',
  );
}
